Port = 6283
PeerModeAuthor = true
PeerModeDHTNode = true
BootstrapServer = ""

[Loggers]
  [Loggers.App]
    Enabled = true
    Format = "%{color:cyan}%{message}"
  [Loggers.DHT]
    Enabled = false
    Format = "%{color:yellow}%{time} DHT: %{message}"
  [Loggers.Gossip]
    Enabled = false
    Format = "%{color:blue}%{time} Gossip: %{message}"
  [Loggers.TestPassed]
    Enabled = true
    Format = "%{color:green}%{message}"
  [Loggers.TestFailed]
    Enabled = true
    Format = "%{color:red}%{message}"
  [Loggers.TestInfo]
    Enabled = true
    Format = "%{message}"
