version: '3'

services:
  service.chain:
    build:
      context: .
      dockerfile: Dockerfile.seedService
    volumes:
      - seed:/chain.seeded
      - ./Scripts:/Scripts
    command: /Scripts/service.chain.seed
  hc:
    build:
      context: .
      dockerfile: Dockerfile.serveInstance
    ports:
      - "3141"
    volumes:
      - seed:/chain.seeded
      - ./Scripts:/Scripts
    command: /Scripts/chain.joinAndServe
    #command: /bin/sh
    depends_on: [service.chain]

volumes:
  seed: 
