#!/bin/sh
export scenario={{SCENARIO}}
export role={{ROLE}}


ls /chain.seeded -la

echo "hc init $HOSTNAME"
hc init $HOSTNAME
echo

echo "hc join /.holochain/devchain"
hc join /chain.seeded/devchain devchain
echo
echo "hc serve devchain"
hc test $scenario $role
echo

